name: CI

on:
  push:
    branches: [ main ]
    
 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: List all ORIGINAL files
        run: ls

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Run Python Script
        run: python create-file.py

      - name: List all NEW files
        run: ls
